### ISSUE TITLE
(MAC) BitcoinPrivateDesktopWallet 1.0.1 hit an error when downloading the Z cryptographic proving key

### ISSUE THREAD

**Issue by matd3n** [BTCPrivate/archived-full-node-wallet#22]
Tried restarting the app but still hit the same error.

<img width="569" alt="screen shot 2018-03-04 at 11 24 31" src="https://user-images.githubusercontent.com/21962140/36942211-a977e348-1f9f-11e8-9bb4-4b3bec7fc15e.png">

**Comment by matd3n** [comment]
I had the latest Java 8. Trying with JDK 9.0.4

**Comment by matd3n** [comment]
Ran with JDK 9.0.4 and got this new error:

[main] [Sun Mar 04 11:50:49 ICT 2018] [ERROR] Unexpected error:  
java.io.IOException: com.eclipsesource.json.ParseException: Expected value at 1:1
	at com.vaklinov.zcashui.ZCashClientCaller.getDaemonRawRuntimeInfo(ZCashClientCaller.java:199)
	at com.vaklinov.zcashui.StartupProgressDialog.waitForStartup(StartupProgressDialog.java:131)
	at com.vaklinov.zcashui.ZCashUI.main(ZCashUI.java:633)
Caused by: com.eclipsesource.json.ParseException: Expected value at 1:1
	at com.eclipsesource.json.JsonParser.error(JsonParser.java:490)
	at com.eclipsesource.json.JsonParser.expected(JsonParser.java:486)
	at com.eclipsesource.json.JsonParser.readValue(JsonParser.java:193)
	at com.eclipsesource.json.JsonParser.parse(JsonParser.java:152)
	at com.eclipsesource.json.JsonParser.parse(JsonParser.java:91)
	at com.eclipsesource.json.Json.parse(Json.java:295)
	at com.vaklinov.zcashui.ZCashClientCaller.getDaemonRawRuntimeInfo(ZCashClientCaller.java:195)
	... 2 more

**Comment by Pega88** [comment]
Hi @matd3n ,
Can you also include the daemon logs? As the daemon threw an error the wallet can't handle, it would be good to see the error on daemon.
Should be under
~/Library/Application Support/BTCPrivate/debug.log

**Comment by ootisra** [comment]
I found the folder but cannot find debug.log

**Comment by ootisra** [comment]
I finally found the debug.log, hope you can help me

Thanks

**Comment by Pega88** [comment]
was the debug file in another folder? can you share the latest lines of debug.log file with u?

**Comment by ootisra** [comment]
[BitcoinPrivateGUIWallet_2018_3_debug.log](https://github.com/BTCPrivate/bitcoin-private-full-node-wallet/files/1778636/BitcoinPrivateGUIWallet_2018_3_debug.log)
this is my log file

**Comment by matd3n** [comment]
My debug log was found here
~/Library/Application\ Support/BTCPrivateDesktopWallet/BitcoinPrivateGUIWallet_2018_3_debug.log

[BitcoinPrivateGUIWallet_2018_3_debug.log](https://github.com/BTCPrivate/bitcoin-private-full-node-wallet/files/1778657/BitcoinPrivateGUIWallet_2018_3_debug.log)

Cheers
